### ISSUE TITLE
stuck in the ladder bug

### ISSUE THREAD

**Issue by parakatins** [WarrenHood/SlidingCompany#3]
when you jump and use the ladder, you get stuck, and if you have the sliding animation, you slide away from the ladder and get completely stuck

**Comment by WarrenHood** [comment]
Thanks for finding this, I'll fix this after January 3rd, currently not at home

**Comment by ricky-davis** [comment]
I've created a PR that fixes this here: https://github.com/WarrenHood/SlidingCompany/pull/5

**Comment by WarrenHood** [comment]
Hi @parakatins this should be fixed in 1.0.7. Please confirm that this is fixed and I'll close this

**Comment by parakatins** [comment]
> Hi @parakatins this should be fixed in 1.0.7. Please confirm that this is fixed and I'll close this

hello, 
The bug of sliding off the stairs is fixed, however I still get stuck when I jump and use the stairs, not exactly stuck but extremely slow and buggy

**Comment by ricky-davis** [comment]
What he's referring to, I believe my PR fixed as well

**Comment by parakatins** [comment]
> What he's referring to, I believe my PR fixed as well


I tested it with just this mod and when I use the ladder it's normal, but when I jump and use the ladder I get stuck

**Comment by ricky-davis** [comment]
Yep, that is still an issue, just tested. My PR had this line:
https://github.com/ricky-davis/SlidingCompany/blob/65a70b7017627597e393ae666bacaff4b87a66a0/SlidingCompany/PlayerSlideController.cs#L252
to fix it.
The velocity is still being applied while climbing (even though slideSpeed is 0), causing stuttering.
